version: '3.8'

services:
  moodle:
    build: .
    container_name: moodle-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - moodle_data:/var/moodledata
      - ./config.php:/var/www/html/config.php
    environment:
      - MOODLE_DB_HOST=moodle_db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASS=your_password_here
    depends_on:
      - moodle_db

  moodle_db:
    image: mysql:8.0
    container_name: moodle-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_here
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=your_password_here
    volumes:
      - moodle_mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  moodle_data:
  moodle_mysql: 