name: Deploy Moodle to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t mohsenmn2079/moodle:latest .
        docker push mohsenmn2079/moodle:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Pull latest image
          docker pull mohsenmn2079/moodle:latest
          
          # Stop and remove old containers
          docker stop moodle-app moodle-db || true
          docker rm moodle-app moodle-db || true
          
          # Start new containers
          docker-compose up -d
          
          # Clean up old images
          docker image prune -f 